# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/RedundantReturn:
  Enabled: false

Naming/MethodName:
  Enabled: true
  AllowedPattern: '^[a-z][A-Za-z0-9]*$'
