# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Naming/MethodName:
  Enabled: false

# Turn off redundant-to_s
Lint/RedundantStringCoercion:
  Enabled: false

# (Optional) Relax string-literal style
Style/StringLiterals:
  Enabled: false  
